### ISSUE TITLE
New Command [--nogui]

### ISSUE THREAD

**Issue by ThKattanek** [ThKattanek/emu64#106]
Originally reported by: **Thorsten Kattanek (Bitbucket: [tkattanek](https://bitbucket.org/tkattanek), GitHub: Unknown)**

----------------------------------------

Bei dieser Option soll emu64 ohne GUI starten. Also nur das C64 Fenster.

----------------------------------------
- Bitbucket: https://bitbucket.org/tkattanek/emu64/issue/106

**Comment by mrdudz** [comment]
now that i can build and run emu64 on my box again due to the qt5 move, i'd like to push this feature request again :) it would make running emu64 in the vice testbench a lot more convenient (ie i can just run it in the background while doing other stuff).

while at it, please also add a "--minimized" option that makes the emu start minimized to tray. depending on the code, this might be easier than "no gui" even, and serves the same purpose. thanks!

**Comment by ThKattanek** [comment]
i have this issue added to the to do list for the active project 5.0.18. :) yes the option --minimized is simplyer implements as --no gui

**Comment by ThKattanek** [comment]
I have the command --minimized added to emu64. The command --no-gui come later.

**Comment by ThKattanek** [comment]
This is now implemented.
